# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IntelliVote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntelliVote
  pod "Parse"
  pod "AlamofireImage"
  target 'IntelliVoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IntelliVoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
